/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "primary-container": "#6cbf3d",
        "on-secondary-container": "#576379",
        "secondary-fixed-dim": "#bbc7e0",
        "inverse-surface": "#2d3135",
        "surface-container": "#ebeef3",
        "tertiary-container": "#77b4c5",
        "on-surface-variant": "#404a39",
        "on-tertiary-fixed-variant": "#004e5d",
        "primary-fixed": "#a1f96f",
        "error": "#ba1a1a",
        "surface-container-high": "#e5e8ee",
        "on-surface": "#181c20",
        "inverse-primary": "#86db56",
        "secondary-fixed": "#d7e3fd",
        "on-secondary-fixed-variant": "#3c475c",
        "surface": "#f7f9ff",
        "on-primary-fixed": "#082100",
        "tertiary-fixed-dim": "#93d0e1",
        "surface-container-lowest": "#ffffff",
        "secondary": "#535f75",
        "on-primary-fixed-variant": "#1f5100",
        "secondary-container": "#d4e0fa",
        "inverse-on-surface": "#eef1f6",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#001f26",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#afecfe",
        "primary": "#2c6c00",
        "surface-dim": "#d7dae0",
        "primary-fixed-dim": "#86db56",
        "on-secondary-fixed": "#101c2f",
        "on-tertiary-container": "#004653",
        "background": "#f7f9ff",
        "surface-variant": "#e0e3e8",
        "surface-tint": "#2c6c00",
        "on-primary": "#ffffff",
        "surface-container-low": "#f1f4f9",
        "outline-variant": "#c0cab4",
        "on-error-container": "#93000a",
        "on-primary-container": "#1c4900",
        "surface-container-highest": "#e0e3e8",
        "surface-bright": "#f7f9ff",
        "outline": "#707a67",
        "tertiary": "#256676",
        "on-background": "#181c20",
        "muted": "#e2e8f0",
        "muted-foreground": "#64748b"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xl": "2rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "margin": "2rem",
        "space-md": "1rem",
        "gutter-dense": "1rem",
        "gutter": "1.5rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-xs": ["Inter", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "heading": ["Space Grotesk", "sans-serif"],
        "sans": ["Inter", "system-ui", "sans-serif"]
      },
      fontSize: {
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-xl": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "label-xs": ["11px", { "lineHeight": "14px", "letterSpacing": "0.03em", "fontWeight": "600" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-sm": ["16px", { "lineHeight": "24px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
